spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/res?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: root
    password: a
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format-sql: true
logging:
  level:
    root: warn
    org.springframework: warn
    com.yc: info
  file:
    path: ./logs
    name: yclogs
server:
  servlet:
    session:
      timeout: 60000
    context-path: /jpa
  port: 80
swagger:
  enabled: true